# ----------------HOW TO USE YAML  --------------------#
# There is an example of how to use YAML file in the bottom of this file.

# ---------------- Test -----------------#
setup:
    time: false
    sequence: [0,3,2,1] 
    # the 1st item is 0, it means the 1st mole will pop up from the 1st hole.
    holeNum: 5
    # holeNum should be equal to the length of sequence.
    positions: [20,500,  20,1000,  220,500,  220,1000 ,420,1000  ]
    # positions should be of length 2*holeNum
    maxRepeat : 1 # the max number of repeat sequence
    peepMinTime: 800 # miliseconds
    peepMaxTime: 2000 # miliseconds
    showUpUntilHit:
    backGroundColor: 
    respondeTime:
    popAllInOnce:
    In one trail: 
    restTime: 10 # seconds.
    greatScore: 20 



# ---------------- WELCOME MESSAGE -----------------#
welcome:
     stimulus: "Welcome to the experiment. Press any key to begin!"

# ----------------INSTRUCTIONS --------------------#
instructions:
    stimulus: >
        <p>In this experiment, a circle will appear in the center
        of the screen.</p><p>If the circle is <strong>blue</strong>,
        press the letter F on the keyboard as fast as you can.</p>
        <p>If the circle is <strong>orange</strong>, press the letter J
        as fast as you can.</p>
        <div style='width: 700px;'>
        <div style='float: left;'><img src='img/blue.png'></img>
        <p class='small'><strong>Press the F key</strong></p></div>
        <div class='float: right;'><img src='img/orange.png'></img>
        <p class='small'><strong>Press the J key</strong></p></div>
        </div>
        <p>Press any key to begin.</p>


# --------------- WEB-CAM RECORDER -----------------#
#recorder:
    #stimulus: >
        
# --------------- Game(Exposure) -----------------#
game:
    stimulus: > 
      <div class="start-screen">    
      <div class="splash-screen"> 
      <div class="button">
        <button>Start</button>
        <div class="show-score"></div>
      </div>
        </div>
      </div>
      <div class="score-block">
        <span class="score">0</span>
      </div>

      <div class="game">
        <div class="hole hole1">
          <div class="mole"></div>
        </div>
        <div class="hole hole2">
          <div class="mole"></div>
        </div>
        <div class="hole hole3">
          <div class="mole"></div>
        </div>
        <div class="hole hole4">
          <div class="mole"></div>
        </div>
        <div class="hole hole5">
          <div class="mole"></div>
        </div>
        <div class="hole hole6">
          <div class="mole"></div>
        </div>
      </div>
      <audio src="sounds/bonk.WAV"></audio>
      <script src="js/app.js"></script>


# ----------------TEST TRIAL --------------------#
test_stimuli:
    tag: 'test'
    blue:
        path: "img/blue.png"
        key: 'f'
    orange:
        path: "img/orange.png"
        key: 'j'

fixation:
    stimulus: '<div style="font-size:60px;">+</div>'
    durations_possibilities: [250, 500, 750, 1000, 1250, 1500, 1750, 2000]
    tag: 'fixation'



# ----------------HOW TO USE YAML  --------------------#
# person:
#     name: &name "mike" #  & sign is a anchor tag, which can be referenced in yaml file.
#     occupation: 'programmer'
#     age: !!float 23 # force integer 23 to become a float 23.0
#     gpa: !!str 3.5  # force 3.5 to become a string "3.5"
#     fav_num: 1e+10
#     male: true
#     birthday: 1994-02-06 14:33:22
#     flasws: null
#     hobbies:
#         - hiking # use hyphen before a list item
#         - movies
#     movies: ["Dark Nnight", "Good Will Hunting"]
#     friends:
#         - name: "Steph"
#           age: 22
#         - {name: "Adam", age: 22}
#     description: > # render the content below in one line.
#         This message will
#         be rendered in
#         one line.
#     signature: |  # render the content below and keep the format.
#         mike
#         Email - test@test.com
#     id:  *name # reference from &name, which is  "mike"
#         var1: value1
#     base: &base
#         var1: value1
#     foo:
#         <<: *base # var1: value1
# ----------------HOW TO USE YAML --------------------#
