# use theme just-the docs
remote_theme: pmarsceill/just-the-docs

# set title?
title: "Child Lang lab EXP"

# enable search
search_enabled: false

# aux links for upper right navigation
aux_links:
  "Visit our public website":
    - "//kschuler.github.io/childlanglab"

